import type {Metadata} from "next";
import QueryProvider from './providers/QueryProvider'
import {ReactNode} from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <QueryProvider locals={{}}>
                    <Header/>
                    {children}
                    <Footer/>
                </QueryProvider>
            </body>
        </html>
    );
}
