import type {Metadata} from "next";
import localFont from "next/font/local";
import QueryProvider from './providers/QueryProvider'
import {Box, Flex} from "@chakra-ui/react";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <QueryProvider locals={{}}>
                <Flex as="body" minH="100vh" h='100%' w='100%' className={`${geistSans.variable} ${geistMono.variable}`}>
                    <Box as="main" flex="1 0 auto" w="100%">
                        <Header/>
                            {children}
                        <Footer/>
                    </Box>
                </Flex>
            </QueryProvider>
        </html>
    );
}
